update workflow

diff --git a/.github/workflows/cygwin.yml b/.github/workflows/cygwin.yml
--- a/.github/workflows/cygwin.yml
+++ b/.github/workflows/cygwin.yml
@@ -47,7 +47,13 @@ jobs:
       run: |
         mkdir build install
         (cd winsup && ./autogen.sh)
-        (cd build && ../configure --target=${{ matrix.target }} --prefix=$(realpath $(pwd)/../install) )
+        (cd build && ../configure \
+          --target=${{ matrix.target }} \
+          --prefix=$(realpath $(pwd)/../install) \
+          CFLAGS="-D__MSYS__" \
+          CXXFLAGS="-D__MSYS__ -Wno-error=unused-but-set-variable" \
+          CCASFLAGS="-D__MSYS__" \
+          MINGW_CXXFLAGS="-Wno-error=unused-but-set-variable" )
         make -C build
         make -C build/*/newlib info man
         make -C build install
@@ -58,9 +64,6 @@ jobs:
       env:
         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
       run: |
-        # pushes to main are deployed as preview
-        # pushes to cygwin-n.n.n (but not 'cygwin-n.n.n.dev') tags are deployed as stable
-        # other references are ignored by this step
         case "${{ github.ref }}" in
           refs/heads/main)
             DEST='preview'
@@ -72,15 +75,11 @@ jobs:
             exit 0
             ;;
         esac
-        # unfuck github fuckery of HOME in a container
         unset HOME
-        # add the hosts public key to known_hosts
         mkdir -p ~/.ssh/
         echo "cygwin.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoejTnTCbXaIIMYfbX7t4tYUOQ2bTxZC3e/td3BageF" >> ~/.ssh/known_hosts
-        # load the key (restricted to scp only) into ssh-agent
         ssh-agent -a $SSH_AUTH_SOCK > /dev/null
         ssh-add - <<< "${{ secrets.SSH_KEY }}"
-        # 'make install' doesn't install faq, so instead just deploy from build directory
         scp -pr build/*/winsup/doc/{cygwin-api,cygwin-ug-net,faq} cygwin-admin@cygwin.com:/sourceware/www/sourceware/htdocs/cygwin/doc/${DEST}/
       if: env.HAS_SSH_KEY == 'true'
 
@@ -95,98 +94,88 @@ jobs:
     name: Windows native ${{ matrix.pkgarch }}
 
     steps:
-    # checkout action uses the native git (we can avoid this messing up line
-    # endings, but this could still be dangerous e.g if we need symlinks in the
-    # repo)
     - run: git config --global core.autocrlf input
-    # remove inheritable permissions since they break assumptions testsuite
-    # makes about file modes
+
     - name: adjust permissions
       run: |
         icacls . /inheritance:r
         icacls . /grant Administrators:F
+
     - uses: actions/checkout@v3
 
-    # install cygwin and build tools
-    - name: Install Cygwin
-      uses: cygwin/cygwin-install-action@master
+    # install MSYS2 and build tools
+    - name: Install MSYS2
+      uses: msys2/setup-msys2@v2
       with:
-        platform: ${{ matrix.pkgarch }}
-        packages: >-
-          autoconf,
-          automake,
-          busybox,
-          cocom,
-          cygutils-extra,
-          dblatex,
-          dejagnu,
-          docbook-xml45,
-          docbook-xsl,
-          docbook2X,
-          gcc-g++,
-          gettext-devel,
-          libiconv,
-          libiconv-devel,
-          libzstd-devel,
-          make,
-          mingw64-${{ matrix.pkgarch }}-gcc-g++,
-          mingw64-${{ matrix.pkgarch }}-zlib,
-          mingw64-i686-gcc-g++,
-          mingw64-i686-zlib,
-          patch,
-          perl,
-          python39-lxml,
-          python39-ply,
-          texlive-collection-fontsrecommended,
-          texlive-collection-latexrecommended,
-          texlive-collection-pictures,
-          xmlto,
+        msystem: MSYS
+        update: true
+        install: >-
+          msys2-devel
+          base-devel
+          autotools
+          cocom
+          dejagnu
+          diffutils
+          gcc
+          gettext-devel
+          libiconv-devel
+          libzstd-devel
+          make
+          mingw-w64-cross-crt
+          mingw-w64-cross-gcc
+          mingw-w64-cross-zlib
+          patch
+          perl
           zlib-devel
+          xmlto
+          docbook-xsl
+          git
 
     # build
-    - name: Build Cygwin
-      run: >-
-        export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32 &&
-        mkdir build install &&
-        (cd winsup; ./autogen.sh) &&
-        cd build &&
-        ../configure --prefix=$(realpath $(pwd)/../install) -v 
-        CFLAGS="-D__MSYS__"
-        CXXFLAGS="-D__MSYS__"
-        CCASFLAGS="-D__MSYS__" &&
-        MINGW_CXXFLAGS="-Wno-unused-but-set-variable" &&
-        export MAKEFLAGS=-j$(nproc) &&
-        make &&
-        make install &&
-        (cd */newlib; make info man) &&
-        (cd */newlib; make install-info install-man)
-      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
-
-    # Check crt0.o is a SEPARATE step at correct indentation
-    - name: Check crt0.o symbol
+    - name: Build
+      shell: msys2 {0}
       run: |
-        nm /usr/lib/crt0.o | grep -i crt0
-        # If output shows cygwin_crt0, recompile with __MSYS__
-        if nm /usr/lib/crt0.o | grep -q "cygwin_crt0"; then
-          echo "WARNING: crt0.o calls cygwin_crt0, recompiling with __MSYS__..."
-          gcc -D__MSYS__ -c ../winsup/cygwin/crt0.c -o /usr/lib/crt0.o
-        fi
-      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
+        mkdir build install
+        (cd winsup && ./autogen.sh)
+        cd build
+        ../configure \
+          --prefix=$(realpath $(pwd)/../install) \
+          -v \
+          CFLAGS="-D__MSYS__" \
+          CXXFLAGS="-D__MSYS__ -Wno-error=unused-but-set-variable" \
+          CCASFLAGS="-D__MSYS__" \
+          MINGW_CXXFLAGS="-Wno-error=unused-but-set-variable"
+        make -j$(nproc)
+        make install
+        (cd */newlib; make info man)
+        (cd */newlib; make install-info install-man)
 
+    # verify crt0.o is the MSYS2 version before running tests
+    - name: Verify crt0.o
+      shell: msys2 {0}
+      run: |
+        echo "=== crt0.o symbols ==="
+        nm /usr/lib/crt0.o | grep -i crt0 || true
+        if nm /usr/lib/crt0.o | grep -q "cygwin_crt0"; then
+          echo "ERROR: crt0.o is from Cygwin not MSYS2, something is wrong"
+          exit 1
+        else
+          echo "OK: crt0.o correctly references msys_crt0"
+        fi
 
     # test
-    - name: Test Cygwin
-      run: >-
-        export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32 &&
-        export MAKEFLAGS=-j$(nproc) &&
-        cd build &&
-        (export PATH=${{ matrix.target }}/winsup/testsuite/testinst/bin:${PATH} && cmd /c $(cygpath -wa ${{ matrix.target }}/winsup/cygserver/cygserver) &) &&
-        (cd ${{ matrix.target }}/winsup; make check AM_COLOR_TESTS=always
-        CFLAGS="-D__MSYS__"
-        CXXFLAGS="-D__MSYS__"
-        CCASFLAGS="-D__MSYS__")
-      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
-
+    - name: Test
+      shell: msys2 {0}
+      run: |
+        export MAKEFLAGS=-j$(nproc)
+        cd build
+        export PATH=$(realpath ${{ matrix.target }}/winsup/testsuite/testinst/bin):${PATH}
+        (cmd /c $(cygpath -wa ${{ matrix.target }}/winsup/cygserver/cygserver) &)
+        cd ${{ matrix.target }}/winsup
+        make check AM_COLOR_TESTS=always \
+          CFLAGS="-D__MSYS__" \
+          CXXFLAGS="-D__MSYS__" \
+          CCASFLAGS="-D__MSYS__"
 
     # upload test logs to facilitate investigation of problems
     - name: Upload test logs
@@ -198,6 +187,7 @@ jobs:
           build/${{ matrix.target }}/winsup/testsuite/**/*.trs
       if: ${{ !cancelled() }}
 
-    # workaround problems with actions/checkout post-run step using cygwin git
+    # no longer needed since we use MSYS2 not Cygwin, but kept as safety measure
     - name: Avoid actions/checkout post-run step using Cygwin git
       run: bash -c 'rm /usr/bin/git.exe'
+      continue-on-error: true
