update workflowv234

diff --git a/.github/workflows/cygwin.yml b/.github/workflows/cygwin.yml
--- a/.github/workflows/cygwin.yml
+++ b/.github/workflows/cygwin.yml
@@ -3,81 +3,103 @@ name: cygwin
 on: workflow_dispatch
 
 jobs:
-    windows-build:
-        runs-on: windows-latest
-        strategy:
-          fail-fast: false
-          matrix:
-            include:
-            - target: x86_64-pc-cygwin
-              pkgarch: x86_64
-        name: Windows native ${{ matrix.pkgarch }}
+  windows-build:
+    runs-on: windows-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - target: x86_64-pc-cygwin
+          pkgarch: x86_64
+    name: Windows native ${{ matrix.pkgarch }}
 
-        steps:
-        - run: git config --global core.autocrlf input
+    steps:
+    - run: git config --global core.autocrlf input
 
-        - uses: actions/checkout@v4
-          with:
-            fetch-depth: 1
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 1
 
-        - name: Install MSYS2
-          uses: msys2/setup-msys2@v2
-          with:
-            msystem: MSYS
-            update: true
-            install: >-
-              msys2-devel
-              base-devel
-              autotools
-              cocom
-              dejagnu
-              gcc
-              gettext-devel
-              libiconv-devel
-              libzstd-devel
-              make
-              mingw-w64-cross-crt
-              mingw-w64-cross-gcc
-              mingw-w64-cross-zlib
-              perl
-              zlib-devel
+    - name: Install MSYS2
+      uses: msys2/setup-msys2@v2
+      with:
+        msystem: MSYS
+        update: true
+        install: >-
+          msys2-devel
+          base-devel
+          autotools
+          cocom
+          dejagnu
+          gcc
+          gettext-devel
+          libiconv-devel
+          libzstd-devel
+          make
+          mingw-w64-cross-crt
+          mingw-w64-cross-gcc
+          mingw-w64-cross-zlib
+          perl
+          zlib-devel
 
-        - name: Build
-          shell: msys2 {0}
-          run: |
-            (cd winsup && ./autogen.sh)
-            mkdir build && cd build
-            ../configure \
-              --prefix=/usr \
-              --disable-doc \
-              CFLAGS="-D__MSYS__" \
-              CXXFLAGS="-D__MSYS__ -Wno-error=unused-but-set-variable" \
-              CCASFLAGS="-D__MSYS__" \
-              MINGW_CXXFLAGS="-Wno-error=unused-but-set-variable"
-            make -j$(nproc)
-            make install
+    - name: Patch unused variable warning
+      shell: msys2 {0}
+      run: |
+        sed -i 's/int count_path_items = 0;/int count_path_items = 0; (void)count_path_items;/' winsup/utils/mingw/cygcheck.cc
 
-        - name: Test
-          shell: msys2 {0}
-          run: |
-            export MAKEFLAGS=-j$(nproc)
-            cd build
-            TESTINST=$(realpath ${{ matrix.target }}/winsup/testsuite/testinst/bin 2>/dev/null \
-              || echo "${{ matrix.target }}/winsup/testsuite/testinst/bin")
-            export PATH="${TESTINST}:${PATH}"
-            cygpath -wa ${{ matrix.target }}/winsup/cygserver/cygserver \
-              | xargs cmd /c &
-            cd ${{ matrix.target }}/winsup
-            make check AM_COLOR_TESTS=always \
-              CFLAGS="-D__MSYS__" \
-              CXXFLAGS="-D__MSYS__" \
-              CCASFLAGS="-D__MSYS__"
+    - name: Build
+      shell: msys2 {0}
+      run: |
+        (cd winsup && ./autogen.sh)
+        mkdir build && cd build
+        ../configure \
+          --prefix=/usr \
+          --disable-doc \
+          --disable-dumper \
+          CFLAGS="-D__MSYS__" \
+          CXXFLAGS="-D__MSYS__ -Wno-error=unused-but-set-variable" \
+          CCASFLAGS="-D__MSYS__" \
+          MINGW_CXXFLAGS="-Wno-error=unused-but-set-variable"
+        make -j$(nproc) MINGW_CXXFLAGS="-Wno-error=unused-but-set-variable"
 
-        - name: Upload test logs
-          uses: actions/upload-artifact@v4
-          with:
-            name: testlogs
-            path: |
-              build/${{ matrix.target }}/winsup/testsuite/**/*.log
-              build/${{ matrix.target }}/winsup/testsuite/**/*.trs
-          if: ${{ !cancelled() }}
+    - name: Install to staging directory
+      shell: msys2 {0}
+      run: |
+        cd build
+        # Install to _dest, never directly to /usr
+        # avoids fork failure from overwriting the running msys-2.0.dll
+        make DESTDIR="$(pwd)/../_dest" install
+
+    - name: Test
+      shell: msys2 {0}
+      run: |
+        export MAKEFLAGS=-j$(nproc)
+        cd build
+        # Point PATH to staged runtime so tests use our built DLL
+        DESTDIR=$(realpath ../_dest)
+        TESTINST=$(realpath ${{ matrix.target }}/winsup/testsuite/testinst/bin 2>/dev/null \
+          || echo "${{ matrix.target }}/winsup/testsuite/testinst/bin")
+        export PATH="${DESTDIR}/usr/bin:${TESTINST}:${PATH}"
+        # Start cygserver from staged install
+        cygpath -wa ${{ matrix.target }}/winsup/cygserver/cygserver \
+          | xargs cmd /c &
+        cd ${{ matrix.target }}/winsup
+        make check AM_COLOR_TESTS=always \
+          CFLAGS="-D__MSYS__" \
+          CXXFLAGS="-D__MSYS__" \
+          CCASFLAGS="-D__MSYS__"
+
+    - name: Upload install
+      uses: actions/upload-artifact@v4
+      with:
+        name: install
+        path: _dest/
+
+    - name: Upload test logs
+      uses: actions/upload-artifact@v4
+      with:
+        name: testlogs
+        path: |
+          build/${{ matrix.target }}/winsup/testsuite/**/*.log
+          build/${{ matrix.target }}/winsup/testsuite/**/*.trs
+      if: ${{ !cancelled() }}
